name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
    - name: install libusb
      run: wget https://github.com/libusb/libusb/archive/v1.0.26.zip && unzip v1.0.26.zip
    - name: write local properties
      run: echo "libusb.dir=$GITHUB_WORKSPACE/libusb-1.0.26" > $GITHUB_WORKSPACE/local.properties
    - name: Build & test with Gradle
      run: ./gradlew jacocoTestReport --stacktrace
    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
